### ISSUE TITLE
Learning curve fails when there are no iterations happening

### ISSUE THREAD

**Issue by FerriolCalvet** [bbglab/omega#31]
```
2024-10-17 21:24:07,350 - INFO    | omega - ######################################################################
2024-10-17 21:24:07,350 - INFO    | omega - #                                                                    #
2024-10-17 21:24:07,350 - INFO    | omega - #                         Welcome to Omega!                          #
2024-10-17 21:24:07,351 - INFO    | omega - #                                                                    #
2024-10-17 21:24:07,351 - INFO    | omega - #                        Running estimator...                        #
2024-10-17 21:24:07,351 - INFO    | omega - #                          Version: v0.2.0                           #
2024-10-17 21:24:07,352 - INFO    | omega - #          Author: Biomedical Genomics Lab - IRB Barcelona           #
2024-10-17 21:24:07,352 - INFO    | omega - #Support: ferriol.calvet@irbbarcelona.org and ferran.muinos@irbbarcelona.org#
2024-10-17 21:24:07,352 - INFO    | omega - #                                                                    #
2024-10-17 21:24:07,352 - INFO    | omega - ######################################################################
2024-10-17 21:24:07,353 - INFO    | omega - 
2024-10-17 21:24:07,353 - INFO    | omega - Received arguments:
2024-10-17 21:24:07,353 - INFO    | omega - observed_mutations_file: outputs/mutations_per_sample_gene_impact_context.P19_0001_BTR_01.shared.global_loc.gLoc.tsv
2024-10-17 21:24:07,353 - INFO    | omega - mutability_file: outputs/mutability_per_sample_gene_context.P19_0001_BTR_01.shared.global_loc.gLoc.tsv
2024-10-17 21:24:07,353 - INFO    | omega - depths_file: ../depthsexonscons/P19_0001_BTR_01.subset_depths.tsv.gz
2024-10-17 21:24:07,354 - INFO    | omega - vep_annotation_file: ../createpanels/consensuspanels/consensus.exons_splice_sites.tsv
2024-10-17 21:24:07,354 - INFO    | omega - grouping_folder: ./groups/
2024-10-17 21:24:07,354 - INFO    | omega - output_fn: outputs/output_mle.P19_0001_BTR_01.shared.global_loc.tsv
2024-10-17 21:24:07,354 - INFO    | omega - option: mle
2024-10-17 21:24:07,355 - INFO    | omega - cores: 4
2024-10-17 21:24:07,355 - INFO    | omega.estimator - Running in mle mode
2024-10-17 21:24:07,660 - DEBUG   | omega.estimator.assemble - depths annotated
2024-10-17 21:24:07,668 - DEBUG   | omega.estimator.assemble - Samples
2024-10-17 21:24:07,668 - DEBUG   | omega.estimator.assemble - {'P19_0001_BTR_01'}
2024-10-17 21:24:07,669 - DEBUG   | omega.estimator.assemble - Genes
2024-10-17 21:24:07,669 - DEBUG   | omega.estimator.assemble - ['CDKN1A', 'TERT', 'RB1', 'KDM6A', 'PIK3CA', 'RBM10', 'CREBBP', 'STAG2', 'ARID1A', 'FGFR4', 'FGFR3', 'KMT2C', 'TP53', 'NOTCH2', 'EP300', 'KMT2D', 'FOXQ1']
2024-10-17 21:24:07,669 - DEBUG   | omega.estimator.assemble - Impacts
2024-10-17 21:24:07,670 - DEBUG   | omega.estimator.assemble - {'nonsense', 'essential_splice', 'missense'}
2024-10-17 21:24:11,520 - DEBUG   | omega.estimator.assemble - lambdas computed
2024-10-17 21:24:11,526 - DEBUG   | omega.estimator.assemble - response computed
2024-10-17 21:24:11,526 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['missense'], ['KMT2D'], filling the counts with 0s.
2024-10-17 21:24:11,549 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['missense'], ['KMT2D'].
2024-10-17 21:24:11,550 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['nonsense'], ['KMT2D'], filling the counts with 0s.
2024-10-17 21:24:11,550 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['nonsense'], ['KMT2D'].
2024-10-17 21:24:11,551 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['essential_splice'], ['KMT2D'], filling the counts with 0s.
2024-10-17 21:24:11,551 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['essential_splice'], ['KMT2D'].
2024-10-17 21:24:11,552 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['missense'], ['PIK3CA'].
2024-10-17 21:24:11,552 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['nonsense'], ['PIK3CA'], filling the counts with 0s.
2024-10-17 21:24:11,553 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['nonsense'], ['PIK3CA'].
2024-10-17 21:24:11,553 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['essential_splice'], ['PIK3CA'], filling the counts with 0s.
2024-10-17 21:24:11,553 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['essential_splice'], ['PIK3CA'].
2024-10-17 21:24:11,554 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['missense'], ['RB1'], filling the counts with 0s.
2024-10-17 21:24:11,554 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['missense'], ['RB1'].
2024-10-17 21:24:11,554 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['nonsense'], ['RB1'], filling the counts with 0s.
2024-10-17 21:24:11,555 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['nonsense'], ['RB1'].
2024-10-17 21:24:11,555 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['essential_splice'], ['RB1'], filling the counts with 0s.
2024-10-17 21:24:11,556 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['essential_splice'], ['RB1'].
2024-10-17 21:24:11,556 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['missense'], ['TP53'], filling the counts with 0s.
2024-10-17 21:24:11,557 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['missense'], ['TP53'].
2024-10-17 21:24:11,557 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['nonsense'], ['TP53'], filling the counts with 0s.
2024-10-17 21:24:11,557 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['nonsense'], ['TP53'].
2024-10-17 21:24:11,558 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['essential_splice'], ['TP53'], filling the counts with 0s.
2024-10-17 21:24:11,558 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['essential_splice'], ['TP53'].
2024-10-17 21:24:11,558 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['missense'], ['FGFR4'], filling the counts with 0s.
2024-10-17 21:24:11,559 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['missense'], ['FGFR4'].
2024-10-17 21:24:11,559 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['nonsense'], ['FGFR4'], filling the counts with 0s.
2024-10-17 21:24:11,560 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['nonsense'], ['FGFR4'].
2024-10-17 21:24:11,560 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['essential_splice'], ['FGFR4'], filling the counts with 0s.
2024-10-17 21:24:11,560 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['essential_splice'], ['FGFR4'].
2024-10-17 21:24:11,561 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['missense'], ['FOXQ1'], filling the counts with 0s.
2024-10-17 21:24:11,561 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['missense'], ['FOXQ1'].
2024-10-17 21:24:11,561 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['nonsense'], ['FOXQ1'], filling the counts with 0s.
2024-10-17 21:24:11,562 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['nonsense'], ['FOXQ1'].
2024-10-17 21:24:11,562 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['essential_splice'], ['FOXQ1'], filling the counts with 0s.
2024-10-17 21:24:11,563 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['essential_splice'], ['FOXQ1'].
2024-10-17 21:24:11,563 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['missense'], ['ARID1A'], filling the counts with 0s.
2024-10-17 21:24:11,564 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['missense'], ['ARID1A'].
2024-10-17 21:24:11,564 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['nonsense'], ['ARID1A'].
2024-10-17 21:24:11,564 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['essential_splice'], ['ARID1A'], filling the counts with 0s.
2024-10-17 21:24:11,565 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['essential_splice'], ['ARID1A'].
2024-10-17 21:24:11,565 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['missense'], ['KDM6A'], filling the counts with 0s.
2024-10-17 21:24:11,566 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['missense'], ['KDM6A'].
2024-10-17 21:24:11,566 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['nonsense'], ['KDM6A'].
2024-10-17 21:24:11,567 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['essential_splice'], ['KDM6A'], filling the counts with 0s.
2024-10-17 21:24:11,567 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['essential_splice'], ['KDM6A'].
2024-10-17 21:24:11,567 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['missense'], ['STAG2'], filling the counts with 0s.
2024-10-17 21:24:11,568 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['missense'], ['STAG2'].
2024-10-17 21:24:11,568 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['nonsense'], ['STAG2'].
2024-10-17 21:24:11,569 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['essential_splice'], ['STAG2'], filling the counts with 0s.
2024-10-17 21:24:11,569 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['essential_splice'], ['STAG2'].
2024-10-17 21:24:11,569 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['missense'], ['CDKN1A'], filling the counts with 0s.
2024-10-17 21:24:11,570 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['missense'], ['CDKN1A'].
2024-10-17 21:24:11,570 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['nonsense'], ['CDKN1A'].
2024-10-17 21:24:11,570 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['essential_splice'], ['CDKN1A'], filling the counts with 0s.
2024-10-17 21:24:11,571 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['essential_splice'], ['CDKN1A'].
2024-10-17 21:24:11,571 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['missense'], ['CREBBP'], filling the counts with 0s.
2024-10-17 21:24:11,572 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['missense'], ['CREBBP'].
2024-10-17 21:24:11,572 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['nonsense'], ['CREBBP'], filling the counts with 0s.
2024-10-17 21:24:11,573 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['nonsense'], ['CREBBP'].
2024-10-17 21:24:11,573 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['essential_splice'], ['CREBBP'], filling the counts with 0s.
2024-10-17 21:24:11,573 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['essential_splice'], ['CREBBP'].
2024-10-17 21:24:11,574 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['missense'], ['NOTCH2'], filling the counts with 0s.
2024-10-17 21:24:11,574 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['missense'], ['NOTCH2'].
2024-10-17 21:24:11,574 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['nonsense'], ['NOTCH2'], filling the counts with 0s.
2024-10-17 21:24:11,575 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['nonsense'], ['NOTCH2'].
2024-10-17 21:24:11,575 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['essential_splice'], ['NOTCH2'], filling the counts with 0s.
2024-10-17 21:24:11,576 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['essential_splice'], ['NOTCH2'].
2024-10-17 21:24:11,576 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['missense'], ['FGFR3'], filling the counts with 0s.
2024-10-17 21:24:11,576 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['missense'], ['FGFR3'].
2024-10-17 21:24:11,577 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['nonsense'], ['FGFR3'], filling the counts with 0s.
2024-10-17 21:24:11,577 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['nonsense'], ['FGFR3'].
2024-10-17 21:24:11,577 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['essential_splice'], ['FGFR3'], filling the counts with 0s.
2024-10-17 21:24:11,578 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['essential_splice'], ['FGFR3'].
2024-10-17 21:24:11,578 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['missense'], ['EP300'], filling the counts with 0s.
2024-10-17 21:24:11,579 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['missense'], ['EP300'].
2024-10-17 21:24:11,579 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['nonsense'], ['EP300'], filling the counts with 0s.
2024-10-17 21:24:11,579 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['nonsense'], ['EP300'].
2024-10-17 21:24:11,580 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['essential_splice'], ['EP300'], filling the counts with 0s.
2024-10-17 21:24:11,580 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['essential_splice'], ['EP300'].
2024-10-17 21:24:11,581 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['missense'], ['RBM10'], filling the counts with 0s.
2024-10-17 21:24:11,581 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['missense'], ['RBM10'].
2024-10-17 21:24:11,581 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['nonsense'], ['RBM10'], filling the counts with 0s.
2024-10-17 21:24:11,582 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['nonsense'], ['RBM10'].
2024-10-17 21:24:11,582 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['essential_splice'], ['RBM10'].
2024-10-17 21:24:11,583 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['missense'], ['KMT2C'], filling the counts with 0s.
2024-10-17 21:24:11,583 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['missense'], ['KMT2C'].
2024-10-17 21:24:11,584 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['nonsense'], ['KMT2C'], filling the counts with 0s.
2024-10-17 21:24:11,584 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['nonsense'], ['KMT2C'].
2024-10-17 21:24:11,584 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['essential_splice'], ['KMT2C'], filling the counts with 0s.
2024-10-17 21:24:11,585 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['essential_splice'], ['KMT2C'].
2024-10-17 21:24:11,585 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['missense'], ['TERT'], filling the counts with 0s.
2024-10-17 21:24:11,586 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['missense'], ['TERT'].
2024-10-17 21:24:11,586 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['nonsense'], ['TERT'], filling the counts with 0s.
2024-10-17 21:24:11,587 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['nonsense'], ['TERT'].
2024-10-17 21:24:11,587 - WARNING | omega.estimator.assemble - No mutations found for ['P19_0001_BTR_01'], ['essential_splice'], ['TERT'], filling the counts with 0s.
2024-10-17 21:24:11,587 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['essential_splice'], ['TERT'].
2024-10-17 21:24:11,591 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['missense'], ['KMT2D', 'PIK3CA', 'RB1', 'TP53', 'FGFR4', 'FOXQ1', 'ARID1A', 'KDM6A', 'STAG2', 'CDKN1A', 'CREBBP', 'NOTCH2', 'FGFR3', 'EP300', 'RBM10', 'KMT2C', 'TERT'].
2024-10-17 21:24:11,593 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['nonsense'], ['KMT2D', 'PIK3CA', 'RB1', 'TP53', 'FGFR4', 'FOXQ1', 'ARID1A', 'KDM6A', 'STAG2', 'CDKN1A', 'CREBBP', 'NOTCH2', 'FGFR3', 'EP300', 'RBM10', 'KMT2C', 'TERT'].
2024-10-17 21:24:11,595 - WARNING | omega.estimator.assemble - Lambdas are 0, we are ignoring this case ['P19_0001_BTR_01'], ['essential_splice'], ['KMT2D', 'PIK3CA', 'RB1', 'TP53', 'FGFR4', 'FOXQ1', 'ARID1A', 'KDM6A', 'STAG2', 'CDKN1A', 'CREBBP', 'NOTCH2', 'FGFR3', 'EP300', 'RBM10', 'KMT2C', 'TERT'].
2024-10-17 21:24:11,604 - INFO    | omega.estimator - Data prepared
0it [00:00, ?it/s]
2024-10-17 21:24:11,611 - CRITICAL | root - Traceback (most recent call last):
  File "/home/fcalvet/miniforge3/envs/omega_env/bin/omega", line 8, in <module>
    sys.exit(omega())
  File "/home/fcalvet/miniforge3/envs/omega_env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/fcalvet/miniforge3/envs/omega_env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/fcalvet/miniforge3/envs/omega_env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/fcalvet/miniforge3/envs/omega_env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/fcalvet/miniforge3/envs/omega_env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/fcalvet/miniforge3/envs/omega_env/lib/python3.10/site-packages/omega/src/globals.py", line 46, in wrapper
    return func(*args, **kwargs)
  File "/home/fcalvet/miniforge3/envs/omega_env/lib/python3.10/site-packages/omega/main.py", line 123, in estimator
    estimator_main(observed_mutations_file, mutability_file, depths_file, vep_annotation_file, grouping_folder, output_fn, option, cores)
  File "/home/fcalvet/miniforge3/envs/omega_env/lib/python3.10/site-packages/omega/src/estimator/main.py", line 112, in run_click
    mle(d, output_fn, cores= int(cores))
  File "/home/fcalvet/miniforge3/envs/omega_env/lib/python3.10/site-packages/omega/src/estimator/main.py", line 76, in mle
    learning_curve_values = pd.DataFrame(df_learning_curve_tmp["learning_curve"].tolist())
  File "/home/fcalvet/miniforge3/envs/omega_env/lib/python3.10/site-packages/pandas/core/frame.py", line 4090, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/fcalvet/miniforge3/envs/omega_env/lib/python3.10/site-packages/pandas/core/indexes/range.py", line 417, in get_loc
    raise KeyError(key)
KeyError: 'learning_curve'
```

**Comment by FerriolCalvet** [comment]
For reproducing the error go to this location or otherwise generate an input where there are no mutations in any of the gene-impact combinations
```
/data/bbg/nobackup/bladder_ts/results/2024-10-17_deepCSA/customomega
```

**Comment by FerriolCalvet** [comment]
the learning curve has been removed so this should not be a problem anymore.
